// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtI8Mj9_CZtinE_9CkCynqdPOOeD_eSvo',
    appId: '1:906910620858:web:4aff9c58e20c9266c6f683',
    messagingSenderId: '906910620858',
    projectId: 'smart-vocab-project',
    authDomain: 'smart-vocab-project.firebaseapp.com',
    databaseURL: 'https://smart-vocab-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-vocab-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXo8sG8wtKMoxI9FtpRf2rTugU_r5w-Vk',
    appId: '1:906910620858:android:b3db949f765bb068c6f683',
    messagingSenderId: '906910620858',
    projectId: 'smart-vocab-project',
    databaseURL: 'https://smart-vocab-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-vocab-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjDkhuxTsAnhcKpNOVlgduP_PLJzLsGUM',
    appId: '1:906910620858:ios:97df338af3106440c6f683',
    messagingSenderId: '906910620858',
    projectId: 'smart-vocab-project',
    databaseURL: 'https://smart-vocab-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-vocab-project.appspot.com',
    iosClientId: '906910620858-a8qffmmh7a43hnv4gfr3ioguktdfhmv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.naimApp',
  );
}
